// Comprehensive India States → Districts → Cities data
export const INDIA_LOCATIONS: Record<string, Record<string, string[]>> = {
  "Andhra Pradesh": {
    "Anantapur": ["Anantapur", "Dharmavaram", "Hindupur", "Guntakal", "Tadpatri"],
    "Chittoor": ["Chittoor", "Tirupati", "Madanapalle", "Punganur", "Srikalahasti"],
    "East Godavari": ["Kakinada", "Rajahmundry", "Amalapuram", "Samalkot"],
    "Guntur": ["Guntur", "Tenali", "Mangalagiri", "Narasaraopet", "Bapatla"],
    "Krishna": ["Vijayawada", "Machilipatnam", "Gudivada", "Nuzvid"],
    "Kurnool": ["Kurnool", "Nandyal", "Adoni", "Yemmiganur"],
    "Nellore": ["Nellore", "Kavali", "Gudur", "Atmakur"],
    "Prakasam": ["Ongole", "Chirala", "Markapur", "Kandukur"],
    "Srikakulam": ["Srikakulam", "Palasa", "Amadalavalasa"],
    "Visakhapatnam": ["Visakhapatnam", "Anakapalle", "Narsipatnam"],
    "Vizianagaram": ["Vizianagaram", "Bobbili", "Nellimarla"],
    "West Godavari": ["Eluru", "Bhimavaram", "Tadepalligudem", "Tanuku"],
    "YSR Kadapa": ["Kadapa", "Proddatur", "Rajampet", "Badvel"],
  },
  "Arunachal Pradesh": {
    "Itanagar Capital Complex": ["Itanagar", "Naharlagun"],
    "Tawang": ["Tawang"],
    "West Kameng": ["Bomdila"],
    "Papum Pare": ["Yupia"],
    "Lower Subansiri": ["Ziro"],
    "East Siang": ["Pasighat"],
    "Changlang": ["Changlang"],
  },
  "Assam": {
    "Kamrup Metropolitan": ["Guwahati", "Dispur"],
    "Kamrup": ["Amingaon", "Rangia", "Hajo"],
    "Cachar": ["Silchar", "Lakhipur"],
    "Dibrugarh": ["Dibrugarh", "Naharkatia", "Chabua"],
    "Jorhat": ["Jorhat", "Titabar", "Mariani"],
    "Nagaon": ["Nagaon", "Hojai", "Lanka"],
    "Sonitpur": ["Tezpur", "Rangapara"],
    "Tinsukia": ["Tinsukia", "Digboi", "Margherita"],
    "Goalpara": ["Goalpara"],
    "Barpeta": ["Barpeta", "Barpeta Road"],
    "Darrang": ["Mangaldai"],
    "Sivasagar": ["Sivasagar", "Nazira"],
  },
  "Bihar": {
    "Patna": ["Patna", "Danapur", "Phulwari Sharif", "Barh"],
    "Gaya": ["Gaya", "Bodh Gaya", "Sherghati"],
    "Muzaffarpur": ["Muzaffarpur", "Sitamarhi"],
    "Bhagalpur": ["Bhagalpur", "Naugachhia"],
    "Purnia": ["Purnia", "Araria"],
    "Darbhanga": ["Darbhanga", "Laheriasarai"],
    "Begusarai": ["Begusarai"],
    "Nalanda": ["Bihar Sharif", "Rajgir"],
    "Vaishali": ["Hajipur", "Mahua"],
    "Samastipur": ["Samastipur"],
    "Saran": ["Chapra"],
    "East Champaran": ["Motihari"],
    "West Champaran": ["Bettiah"],
    "Munger": ["Munger", "Jamalpur"],
    "Rohtas": ["Sasaram", "Dehri"],
  },
  "Chhattisgarh": {
    "Raipur": ["Raipur", "Arang", "Abhanpur"],
    "Durg": ["Durg", "Bhilai", "Rajnandgaon"],
    "Bilaspur": ["Bilaspur", "Mungeli"],
    "Korba": ["Korba"],
    "Raigarh": ["Raigarh"],
    "Jagdalpur": ["Jagdalpur"],
    "Ambikapur": ["Ambikapur"],
    "Janjgir-Champa": ["Janjgir", "Champa"],
    "Dhamtari": ["Dhamtari"],
    "Mahasamund": ["Mahasamund"],
  },
  "Delhi": {
    "New Delhi": ["New Delhi", "Connaught Place", "Karol Bagh", "Saket"],
    "North Delhi": ["Civil Lines", "Model Town", "Sadar Bazaar"],
    "South Delhi": ["Hauz Khas", "Mehrauli", "Greater Kailash", "Defence Colony"],
    "East Delhi": ["Preet Vihar", "Laxmi Nagar", "Mayur Vihar"],
    "West Delhi": ["Rajouri Garden", "Janakpuri", "Dwarka"],
    "Central Delhi": ["Chandni Chowk", "Paharganj", "Daryaganj"],
    "North East Delhi": ["Seelampur", "Shahdara"],
    "South East Delhi": ["Kalkaji", "Badarpur"],
    "South West Delhi": ["Vasant Kunj", "R.K. Puram"],
  },
  "Goa": {
    "North Goa": ["Panaji", "Mapusa", "Bicholim", "Valpoi", "Calangute", "Candolim"],
    "South Goa": ["Margao", "Vasco da Gama", "Ponda", "Quepem", "Canacona"],
  },
  "Gujarat": {
    "Ahmedabad": ["Ahmedabad", "Sanand", "Dholka", "Viramgam", "Bavla"],
    "Surat": ["Surat", "Bardoli", "Kamrej", "Mandvi"],
    "Vadodara": ["Vadodara", "Dabhoi", "Savli", "Padra"],
    "Rajkot": ["Rajkot", "Gondal", "Jetpur", "Dhoraji"],
    "Bhavnagar": ["Bhavnagar", "Palitana", "Sihor", "Mahuva"],
    "Jamnagar": ["Jamnagar", "Dhrol", "Kalavad"],
    "Junagadh": ["Junagadh", "Veraval", "Mangrol", "Keshod"],
    "Gandhinagar": ["Gandhinagar", "Kalol", "Dehgam"],
    "Kutch": ["Bhuj", "Gandhidham", "Anjar", "Mundra", "Mandvi"],
    "Mehsana": ["Mehsana", "Visnagar", "Kadi", "Unjha"],
    "Anand": ["Anand", "Khambhat", "Petlad", "Borsad"],
    "Bharuch": ["Bharuch", "Ankleshwar"],
    "Valsad": ["Valsad", "Vapi", "Navsari", "Dharampur"],
    "Patan": ["Patan", "Siddhpur", "Radhanpur"],
    "Banaskantha": ["Palanpur", "Deesa", "Danta"],
    "Narmada": ["Rajpipla"],
  },
  "Haryana": {
    "Gurgaon": ["Gurgaon", "Sohna", "Pataudi", "Manesar"],
    "Faridabad": ["Faridabad", "Ballabgarh"],
    "Panipat": ["Panipat", "Samalkha", "Israna"],
    "Karnal": ["Karnal", "Nilokheri", "Gharaunda"],
    "Ambala": ["Ambala", "Ambala Cantt", "Barara"],
    "Hisar": ["Hisar", "Hansi", "Barwala"],
    "Rohtak": ["Rohtak", "Meham", "Kalanaur"],
    "Sonipat": ["Sonipat", "Ganaur", "Gohana"],
    "Panchkula": ["Panchkula"],
    "Yamunanagar": ["Yamunanagar", "Jagadhri"],
    "Sirsa": ["Sirsa", "Dabwali", "Ellenabad"],
    "Bhiwani": ["Bhiwani", "Charkhi Dadri"],
    "Jhajjar": ["Jhajjar", "Bahadurgarh"],
    "Rewari": ["Rewari"],
    "Kurukshetra": ["Kurukshetra", "Thanesar", "Shahabad"],
    "Jind": ["Jind", "Safidon", "Narwana"],
    "Kaithal": ["Kaithal", "Pundri"],
    "Mahendragarh": ["Narnaul", "Mahendragarh"],
    "Palwal": ["Palwal", "Hodal"],
    "Nuh": ["Nuh", "Ferozepur Jhirka", "Tauru"],
  },
  "Himachal Pradesh": {
    "Shimla": ["Shimla", "Kufri", "Mashobra", "Theog"],
    "Kangra": ["Dharamsala", "Palampur", "Kangra", "Nurpur"],
    "Kullu": ["Kullu", "Manali", "Bhuntar"],
    "Mandi": ["Mandi", "Sundernagar"],
    "Solan": ["Solan", "Baddi", "Nalagarh", "Kasauli"],
    "Hamirpur": ["Hamirpur"],
    "Una": ["Una"],
    "Bilaspur": ["Bilaspur"],
    "Chamba": ["Chamba", "Dalhousie"],
    "Sirmaur": ["Nahan", "Paonta Sahib"],
    "Kinnaur": ["Reckong Peo", "Kalpa"],
    "Lahaul & Spiti": ["Keylong"],
  },
  "Jammu & Kashmir": {
    "Srinagar": ["Srinagar"],
    "Jammu": ["Jammu"],
    "Anantnag": ["Anantnag"],
    "Baramulla": ["Baramulla", "Sopore"],
    "Udhampur": ["Udhampur"],
    "Kathua": ["Kathua"],
    "Pulwama": ["Pulwama"],
    "Kupwara": ["Kupwara"],
    "Rajouri": ["Rajouri"],
    "Poonch": ["Poonch"],
  },
  "Jharkhand": {
    "Ranchi": ["Ranchi", "Namkum", "Kanke"],
    "Jamshedpur": ["Jamshedpur", "Gamharia", "Mango"],
    "Dhanbad": ["Dhanbad", "Jharia", "Sindri"],
    "Bokaro": ["Bokaro Steel City", "Chas"],
    "Hazaribagh": ["Hazaribagh"],
    "Deoghar": ["Deoghar"],
    "Giridih": ["Giridih"],
    "Dumka": ["Dumka"],
    "Ramgarh": ["Ramgarh"],
    "Chaibasa": ["Chaibasa"],
  },
  "Karnataka": {
    "Bangalore Urban": ["Bangalore", "Whitefield", "Electronic City", "Yelahanka"],
    "Bangalore Rural": ["Devanahalli", "Nelamangala", "Doddaballapur"],
    "Mysore": ["Mysore", "Nanjangud", "Hunsur"],
    "Mangalore": ["Mangalore", "Udupi", "Puttur", "Bantwal"],
    "Hubli-Dharwad": ["Hubli", "Dharwad"],
    "Belgaum": ["Belgaum", "Gokak", "Athani"],
    "Gulbarga": ["Gulbarga", "Chincholi"],
    "Shimoga": ["Shimoga", "Bhadravati"],
    "Davangere": ["Davangere", "Harihar"],
    "Bellary": ["Bellary", "Hospet"],
    "Bijapur": ["Bijapur"],
    "Hassan": ["Hassan", "Belur"],
    "Raichur": ["Raichur", "Sindhanur"],
    "Tumkur": ["Tumkur"],
    "Udupi": ["Udupi", "Kundapura"],
    "Chikmagalur": ["Chikmagalur"],
    "Kodagu": ["Madikeri"],
  },
  "Kerala": {
    "Thiruvananthapuram": ["Thiruvananthapuram", "Neyyattinkara", "Attingal"],
    "Kochi": ["Kochi", "Aluva", "Angamaly", "Perumbavoor"],
    "Kozhikode": ["Kozhikode", "Vadakara", "Koyilandy"],
    "Thrissur": ["Thrissur", "Chalakudy", "Irinjalakuda"],
    "Kollam": ["Kollam", "Punalur", "Karunagappally"],
    "Kannur": ["Kannur", "Thalassery", "Payyanur"],
    "Alappuzha": ["Alappuzha", "Cherthala", "Kayamkulam"],
    "Malappuram": ["Malappuram", "Manjeri", "Tirur", "Ponnani"],
    "Palakkad": ["Palakkad", "Ottapalam", "Shoranur"],
    "Kottayam": ["Kottayam", "Pala", "Changanassery"],
    "Idukki": ["Thodupuzha", "Munnar", "Adimali"],
    "Pathanamthitta": ["Pathanamthitta", "Thiruvalla"],
    "Wayanad": ["Kalpetta", "Sulthan Bathery", "Mananthavady"],
    "Kasaragod": ["Kasaragod"],
  },
  "Madhya Pradesh": {
    "Bhopal": ["Bhopal"],
    "Indore": ["Indore", "Mhow", "Pithampur"],
    "Jabalpur": ["Jabalpur"],
    "Gwalior": ["Gwalior"],
    "Ujjain": ["Ujjain"],
    "Sagar": ["Sagar"],
    "Dewas": ["Dewas"],
    "Satna": ["Satna"],
    "Ratlam": ["Ratlam"],
    "Rewa": ["Rewa"],
    "Katni": ["Katni"],
    "Singrauli": ["Singrauli"],
    "Burhanpur": ["Burhanpur"],
    "Morena": ["Morena"],
    "Khandwa": ["Khandwa"],
    "Chhindwara": ["Chhindwara"],
    "Damoh": ["Damoh"],
    "Vidisha": ["Vidisha"],
    "Khargone": ["Khargone"],
  },
  "Maharashtra": {
    "Mumbai City": ["Mumbai"],
    "Mumbai Suburban": ["Andheri", "Borivali", "Malad", "Goregaon", "Bandra", "Kandivali"],
    "Thane": ["Thane", "Kalyan", "Dombivli", "Ulhasnagar", "Bhiwandi", "Ambernath"],
    "Pune": ["Pune", "Pimpri-Chinchwad", "Lonavala", "Baramati", "Shirur"],
    "Nagpur": ["Nagpur", "Kamptee", "Hingna"],
    "Nashik": ["Nashik", "Malegaon", "Sinnar", "Trimbakeshwar"],
    "Aurangabad": ["Aurangabad", "Paithan", "Vaijapur"],
    "Solapur": ["Solapur", "Pandharpur", "Barshi"],
    "Kolhapur": ["Kolhapur", "Ichalkaranji", "Jaysingpur"],
    "Navi Mumbai": ["Navi Mumbai", "Panvel", "Vashi", "Nerul", "Belapur"],
    "Raigad": ["Alibaug", "Karjat", "Khalapur", "Roha"],
    "Ratnagiri": ["Ratnagiri", "Chiplun", "Dapoli"],
    "Sangli": ["Sangli", "Miraj", "Vita"],
    "Satara": ["Satara", "Karad", "Wai", "Mahabaleshwar"],
    "Ahmednagar": ["Ahmednagar", "Shrirampur", "Rahuri"],
    "Jalgaon": ["Jalgaon", "Bhusawal", "Amalner"],
    "Dhule": ["Dhule", "Shirpur"],
    "Nandurbar": ["Nandurbar", "Shahada"],
    "Palghar": ["Palghar", "Vasai", "Virar", "Boisar"],
    "Osmanabad": ["Osmanabad", "Tuljapur"],
    "Latur": ["Latur", "Udgir"],
    "Beed": ["Beed"],
    "Hingoli": ["Hingoli"],
    "Parbhani": ["Parbhani"],
    "Nanded": ["Nanded"],
    "Washim": ["Washim"],
    "Buldhana": ["Buldhana", "Chikhli", "Khamgaon"],
    "Akola": ["Akola"],
    "Amravati": ["Amravati", "Achalpur"],
    "Yavatmal": ["Yavatmal"],
    "Wardha": ["Wardha"],
    "Chandrapur": ["Chandrapur"],
    "Gadchiroli": ["Gadchiroli"],
    "Bhandara": ["Bhandara"],
    "Gondia": ["Gondia"],
    "Sindhudurg": ["Sindhudurg", "Kudal", "Malvan"],
  },
  "Manipur": {
    "Imphal West": ["Imphal"],
    "Imphal East": ["Porompat"],
    "Thoubal": ["Thoubal"],
    "Bishnupur": ["Bishnupur"],
    "Churachandpur": ["Churachandpur"],
  },
  "Meghalaya": {
    "East Khasi Hills": ["Shillong"],
    "West Garo Hills": ["Tura"],
    "Ri-Bhoi": ["Nongpoh"],
    "West Jaintia Hills": ["Jowai"],
  },
  "Mizoram": {
    "Aizawl": ["Aizawl"],
    "Lunglei": ["Lunglei"],
    "Champhai": ["Champhai"],
  },
  "Nagaland": {
    "Kohima": ["Kohima"],
    "Dimapur": ["Dimapur"],
    "Mokokchung": ["Mokokchung"],
    "Tuensang": ["Tuensang"],
  },
  "Odisha": {
    "Bhubaneswar": ["Bhubaneswar"],
    "Cuttack": ["Cuttack"],
    "Rourkela": ["Rourkela"],
    "Berhampur": ["Berhampur"],
    "Sambalpur": ["Sambalpur"],
    "Puri": ["Puri"],
    "Balasore": ["Balasore"],
    "Baripada": ["Baripada"],
    "Bhadrak": ["Bhadrak"],
    "Jharsuguda": ["Jharsuguda"],
    "Angul": ["Angul", "Talcher"],
    "Koraput": ["Koraput", "Jeypore"],
    "Kendrapara": ["Kendrapara"],
    "Jajpur": ["Jajpur"],
  },
  "Punjab": {
    "Amritsar": ["Amritsar"],
    "Ludhiana": ["Ludhiana", "Khanna"],
    "Jalandhar": ["Jalandhar", "Phagwara", "Nakodar"],
    "Patiala": ["Patiala", "Rajpura", "Nabha"],
    "Bathinda": ["Bathinda"],
    "Mohali": ["Mohali", "Kharar", "Derabassi"],
    "Pathankot": ["Pathankot"],
    "Hoshiarpur": ["Hoshiarpur"],
    "Moga": ["Moga"],
    "Sangrur": ["Sangrur", "Malerkotla"],
    "Firozpur": ["Firozpur"],
    "Gurdaspur": ["Gurdaspur"],
    "Kapurthala": ["Kapurthala"],
    "Muktsar": ["Muktsar"],
    "Mansa": ["Mansa"],
    "Faridkot": ["Faridkot"],
    "Barnala": ["Barnala"],
    "Fazilka": ["Fazilka", "Abohar"],
    "Chandigarh": ["Chandigarh"],
  },
  "Rajasthan": {
    "Jaipur": ["Jaipur", "Sanganer", "Amer", "Chomu"],
    "Jodhpur": ["Jodhpur", "Phalodi"],
    "Udaipur": ["Udaipur", "Salumber", "Rajsamand"],
    "Ajmer": ["Ajmer", "Pushkar", "Beawar", "Kishangarh"],
    "Kota": ["Kota"],
    "Bikaner": ["Bikaner"],
    "Jaisalmer": ["Jaisalmer"],
    "Alwar": ["Alwar", "Bhiwadi", "Behror"],
    "Bhilwara": ["Bhilwara"],
    "Sikar": ["Sikar"],
    "Jhunjhunu": ["Jhunjhunu"],
    "Pali": ["Pali"],
    "Tonk": ["Tonk"],
    "Nagaur": ["Nagaur"],
    "Sri Ganganagar": ["Sri Ganganagar"],
    "Hanumangarh": ["Hanumangarh"],
    "Barmer": ["Barmer"],
    "Chittorgarh": ["Chittorgarh"],
    "Dungarpur": ["Dungarpur"],
    "Banswara": ["Banswara"],
    "Bundi": ["Bundi"],
    "Sawai Madhopur": ["Sawai Madhopur"],
    "Dausa": ["Dausa"],
    "Karauli": ["Karauli"],
    "Dholpur": ["Dholpur"],
    "Bharatpur": ["Bharatpur", "Deeg"],
  },
  "Sikkim": {
    "East Sikkim": ["Gangtok"],
    "South Sikkim": ["Namchi"],
    "West Sikkim": ["Gyalshing"],
    "North Sikkim": ["Mangan"],
  },
  "Tamil Nadu": {
    "Chennai": ["Chennai", "Tambaram", "Avadi", "Ambattur"],
    "Coimbatore": ["Coimbatore", "Pollachi", "Mettupalayam"],
    "Madurai": ["Madurai", "Melur", "Vadipatti"],
    "Salem": ["Salem", "Attur", "Mettur"],
    "Tiruchirappalli": ["Tiruchirappalli", "Srirangam", "Lalgudi"],
    "Tirunelveli": ["Tirunelveli", "Palayamkottai"],
    "Erode": ["Erode", "Gobichettipalayam", "Bhavani"],
    "Vellore": ["Vellore", "Ranipet", "Ambur"],
    "Thoothukudi": ["Thoothukudi"],
    "Thanjavur": ["Thanjavur", "Kumbakonam"],
    "Dindigul": ["Dindigul", "Palani"],
    "Kanchipuram": ["Kanchipuram", "Chengalpattu"],
    "Tirupur": ["Tirupur", "Avinashi"],
    "Nagercoil": ["Nagercoil"],
    "Cuddalore": ["Cuddalore", "Chidambaram"],
    "Karur": ["Karur"],
    "Ramanathapuram": ["Ramanathapuram"],
    "Sivaganga": ["Sivaganga", "Karaikudi"],
    "Virudhunagar": ["Virudhunagar"],
    "Nagapattinam": ["Nagapattinam"],
    "Namakkal": ["Namakkal", "Tiruchengode"],
    "Villupuram": ["Villupuram", "Tindivanam"],
    "Krishnagiri": ["Krishnagiri", "Hosur"],
    "Dharmapuri": ["Dharmapuri"],
    "Nilgiris": ["Ooty", "Coonoor", "Kotagiri"],
    "Perambalur": ["Perambalur"],
    "Ariyalur": ["Ariyalur"],
  },
  "Telangana": {
    "Hyderabad": ["Hyderabad", "Secunderabad"],
    "Rangareddy": ["Shamshabad", "Chevella", "Ibrahimpatnam", "Shadnagar"],
    "Medchal-Malkajgiri": ["Medchal", "Kompally", "Uppal"],
    "Sangareddy": ["Sangareddy"],
    "Warangal Urban": ["Warangal"],
    "Warangal Rural": ["Narsampet"],
    "Nizamabad": ["Nizamabad", "Bodhan"],
    "Karimnagar": ["Karimnagar"],
    "Khammam": ["Khammam"],
    "Mahbubnagar": ["Mahbubnagar"],
    "Nalgonda": ["Nalgonda"],
    "Adilabad": ["Adilabad"],
    "Medak": ["Medak", "Siddipet"],
    "Suryapet": ["Suryapet"],
    "Sircilla": ["Sircilla"],
    "Jagtial": ["Jagtial"],
    "Mancherial": ["Mancherial"],
    "Peddapalli": ["Peddapalli"],
  },
  "Tripura": {
    "West Tripura": ["Agartala"],
    "South Tripura": ["Udaipur"],
    "North Tripura": ["Dharmanagar"],
    "Dhalai": ["Ambassa"],
  },
  "Uttar Pradesh": {
    "Lucknow": ["Lucknow"],
    "Kanpur Nagar": ["Kanpur"],
    "Agra": ["Agra", "Fatehpur Sikri"],
    "Gautam Buddh Nagar": ["Noida", "Greater Noida"],
    "Varanasi": ["Varanasi"],
    "Ghaziabad": ["Ghaziabad", "Loni", "Modinagar"],
    "Meerut": ["Meerut"],
    "Allahabad": ["Prayagraj"],
    "Gorakhpur": ["Gorakhpur"],
    "Bareilly": ["Bareilly"],
    "Aligarh": ["Aligarh"],
    "Moradabad": ["Moradabad"],
    "Saharanpur": ["Saharanpur"],
    "Jhansi": ["Jhansi"],
    "Mathura": ["Mathura", "Vrindavan"],
    "Firozabad": ["Firozabad"],
    "Muzaffarnagar": ["Muzaffarnagar"],
    "Shahjahanpur": ["Shahjahanpur"],
    "Rampur": ["Rampur"],
    "Bulandshahr": ["Bulandshahr"],
    "Hapur": ["Hapur"],
    "Ayodhya": ["Ayodhya", "Faizabad"],
    "Sultanpur": ["Sultanpur"],
    "Unnao": ["Unnao"],
    "Rae Bareli": ["Rae Bareli"],
    "Etawah": ["Etawah"],
    "Mainpuri": ["Mainpuri"],
    "Banda": ["Banda"],
    "Fatehpur": ["Fatehpur"],
    "Hardoi": ["Hardoi"],
    "Sitapur": ["Sitapur"],
    "Lakhimpur Kheri": ["Lakhimpur"],
    "Basti": ["Basti"],
    "Deoria": ["Deoria"],
    "Azamgarh": ["Azamgarh"],
    "Jaunpur": ["Jaunpur"],
    "Mirzapur": ["Mirzapur"],
    "Sonbhadra": ["Sonbhadra", "Robertsganj"],
    "Ballia": ["Ballia"],
    "Gonda": ["Gonda"],
    "Bahraich": ["Bahraich"],
    "Pratapgarh": ["Pratapgarh"],
    "Ambedkar Nagar": ["Akbarpur"],
    "Barabanki": ["Barabanki"],
  },
  "Uttarakhand": {
    "Dehradun": ["Dehradun", "Mussoorie", "Rishikesh"],
    "Haridwar": ["Haridwar", "Roorkee"],
    "Nainital": ["Nainital", "Haldwani", "Ramnagar"],
    "Udham Singh Nagar": ["Rudrapur", "Kashipur", "Jaspur"],
    "Almora": ["Almora"],
    "Pithoragarh": ["Pithoragarh"],
    "Chamoli": ["Chamoli", "Joshimath"],
    "Pauri Garhwal": ["Pauri", "Kotdwar", "Srinagar"],
    "Tehri Garhwal": ["Tehri", "New Tehri"],
    "Champawat": ["Champawat"],
    "Bageshwar": ["Bageshwar"],
    "Rudraprayag": ["Rudraprayag"],
    "Uttarkashi": ["Uttarkashi"],
  },
  "West Bengal": {
    "Kolkata": ["Kolkata"],
    "Howrah": ["Howrah"],
    "North 24 Parganas": ["Barasat", "Barrackpore", "Dum Dum", "Bhatpara"],
    "South 24 Parganas": ["Baruipur", "Diamond Harbour"],
    "Durgapur": ["Durgapur", "Asansol"],
    "Siliguri": ["Siliguri"],
    "Hooghly": ["Chinsurah", "Serampore", "Chandannagar"],
    "Nadia": ["Krishnanagar", "Nabadwip", "Ranaghat"],
    "Burdwan": ["Burdwan"],
    "Midnapore West": ["Midnapore", "Kharagpur"],
    "Midnapore East": ["Tamluk", "Haldia", "Contai"],
    "Murshidabad": ["Berhampore", "Kandi"],
    "Birbhum": ["Suri", "Bolpur", "Shantiniketan"],
    "Bankura": ["Bankura", "Bishnupur"],
    "Purulia": ["Purulia"],
    "Malda": ["Malda", "English Bazar"],
    "Jalpaiguri": ["Jalpaiguri"],
    "Cooch Behar": ["Cooch Behar"],
    "Darjeeling": ["Darjeeling", "Kurseong", "Kalimpong"],
    "Alipurduar": ["Alipurduar"],
  },
  "Ladakh": {
    "Leh": ["Leh"],
    "Kargil": ["Kargil"],
  },
  "Chandigarh": {
    "Chandigarh": ["Chandigarh"],
  },
  "Puducherry": {
    "Puducherry": ["Puducherry"],
    "Karaikal": ["Karaikal"],
    "Mahe": ["Mahe"],
    "Yanam": ["Yanam"],
  },
  "Andaman & Nicobar Islands": {
    "South Andaman": ["Port Blair"],
    "North & Middle Andaman": ["Mayabunder"],
    "Nicobar": ["Car Nicobar"],
  },
  "Dadra and Nagar Haveli and Daman and Diu": {
    "Daman": ["Daman"],
    "Diu": ["Diu"],
    "Dadra and Nagar Haveli": ["Silvassa"],
  },
  "Lakshadweep": {
    "Lakshadweep": ["Kavaratti"],
  },
};

// Helper to get sorted state names
export const getStates = (): string[] => Object.keys(INDIA_LOCATIONS).sort();

// Helper to get districts for a state
export const getDistricts = (state: string): string[] => {
  const districts = INDIA_LOCATIONS[state];
  return districts ? Object.keys(districts).sort() : [];
};

// Helper to get cities for a state and district
export const getCities = (state: string, district: string): string[] => {
  const districts = INDIA_LOCATIONS[state];
  if (!districts) return [];
  return districts[district] || [];
};

// Districts that qualify for Mumbai pricing
export const MUMBAI_DISTRICTS = ["Mumbai City", "Mumbai Suburban", "Thane", "Navi Mumbai", "Palghar"];

// Helper to check if a location qualifies for Mumbai pricing (district-based)
export const isMumbaiCity = (state: string, cityOrDistrict: string): boolean => {
  if (state !== "Maharashtra") return false;
  return MUMBAI_DISTRICTS.includes(cityOrDistrict);
};

// Overload: check using both district and city for maximum compatibility
export const isMumbaiRegion = (state: string, district: string, city?: string): boolean => {
  if (state !== "Maharashtra") return false;
  if (MUMBAI_DISTRICTS.includes(district)) return true;
  if (city && MUMBAI_DISTRICTS.includes(city)) return true;
  // Also match city names that imply Mumbai
  const MUMBAI_CITIES = ["Mumbai", "Navi Mumbai", "Thane", "Palghar"];
  if (city && MUMBAI_CITIES.includes(city)) return true;
  return false;
};
