project_id = "cqdxfvcyrvlttmkuaeda"

[functions.reset-password]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.login-with-secret-code]
verify_jwt = false

[functions.collect-event-payment]
verify_jwt = false

[functions.change-admin-password]
verify_jwt = false

[functions.send-web-push]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.match-artists]
verify_jwt = false

[functions.generate-caricature]
verify_jwt = false

[functions.admin-ai-monitor]
verify_jwt = false

[functions.mini-db-sync]
verify_jwt = false

[functions.google-indexing]
verify_jwt = false

[functions.dynamic-sitemap]
verify_jwt = false
