ALTER TABLE public.event_bookings REPLICA IDENTITY FULL;
ALTER TABLE public.orders REPLICA IDENTITY FULL;
ALTER TABLE public.shop_orders REPLICA IDENTITY FULL;
ALTER TABLE public.payment_history REPLICA IDENTITY FULL;
ALTER TABLE public.profiles REPLICA IDENTITY FULL;