
INSERT INTO public.seo_page_settings (id, page_title, meta_description, seo_keywords, og_title, og_description, og_image, updated_at)
VALUES
('home', 'Custom Hand-Crafted Caricatures Online India | Live Caricature Artists', 'Creative Caricature Club™ — India''s #1 caricature studio. Book live caricature artists for weddings, corporate events, birthdays & parties in Mumbai & across India. Order custom hand-crafted caricatures from photos online.', 'Creative Caricature Club, caricature artist Mumbai, live caricature artist, caricature for wedding, custom caricature online India, book caricature artist, caricature artist near me, event caricature, caricature gift, birthday caricature, corporate caricature, party entertainment, wedding entertainment, Mumbai artist, caricature from photo', 'Creative Caricature Club™ — India''s #1 Caricature Studio', 'Book live caricature artists for weddings & events or order custom hand-crafted caricatures from photos. Serving Mumbai & all of India.', '/logo.png', now()),
('order', 'Order Custom Caricature Online | Get Caricature From Photo', 'Order a custom hand-drawn caricature from your photo. Choose from digital, hand-painted, or couple caricatures. Fast delivery across India. Perfect personalized gift for birthdays, anniversaries & weddings.', 'order caricature online, custom caricature from photo, personalized caricature gift, digital caricature India, hand-drawn caricature, couple caricature, birthday gift caricature, anniversary caricature, caricature delivery India, photo to caricature', 'Order Custom Caricature Online — Creative Caricature Club™', 'Get a stunning custom caricature from your photo. Hand-crafted by professional artists. Fast delivery across India.', '/logo.png', now()),
('book-event', 'Book Live Caricature Artist for Events | Weddings & Parties', 'Book professional live caricature artists for weddings, corporate events, birthday parties, college fests & private gatherings across India. On-the-spot caricature entertainment that wows guests.', 'book caricature artist for event, live caricature wedding, event caricature artist Mumbai, corporate event entertainment, birthday party caricature, wedding entertainment idea, live sketch artist, on-spot caricature, party artist booking, caricature artist hire India', 'Book Live Caricature Artist — Weddings, Parties & Events', 'Hire professional live caricature artists for your event. On-the-spot entertainment for weddings, corporate events & parties across India.', '/logo.png', now()),
('track-order', 'Track Your Caricature Order | Order Status', 'Track your custom caricature order status in real-time. Enter your order ID and registered email or mobile to check the progress of your caricature artwork.', 'track caricature order, order status Creative Caricature Club, check order progress, caricature delivery status, order tracking India', 'Track Your Order — Creative Caricature Club™', 'Check the real-time status of your custom caricature order.', '/logo.png', now()),
('shop', 'Caricature Shop | Ready-Made & Custom Art Prints', 'Browse and buy ready-made caricature art prints, custom frames, and unique caricature merchandise. Affordable caricature gifts delivered across India.', 'caricature shop, buy caricature online, caricature art prints, caricature merchandise, caricature frames, affordable caricature gift, unique art gift India, cartoon portrait shop', 'Caricature Shop — Buy Art Prints & Gifts Online', 'Shop unique caricature art prints, custom frames & merchandise. Affordable gifts delivered across India.', '/logo.png', now()),
('about', 'About Creative Caricature Club™ | India''s Top Caricature Studio', 'Learn about Creative Caricature Club™ — India''s leading caricature studio with 500+ events, 10,000+ happy customers. Professional artists, premium quality, pan-India service.', 'about Creative Caricature Club, caricature studio India, caricature company Mumbai, professional caricature artists, Indian caricature studio, art studio Mumbai, caricature team, artist portfolio', 'About Us — Creative Caricature Club™', 'India''s most trusted caricature studio. 500+ events, 10,000+ happy customers. Professional artists delivering premium quality.', '/logo.png', now()),
('enquiry', 'Enquire Now | Get a Quote for Caricature Services', 'Have questions or need a custom quote? Send us your enquiry for live event caricatures, custom caricatures from photos, or bulk orders. Quick response guaranteed.', 'caricature enquiry, get caricature quote, contact caricature artist, caricature pricing, event caricature cost, custom caricature quote, bulk caricature order, caricature service inquiry', 'Enquire Now — Get Your Caricature Quote', 'Send your enquiry for live event caricatures or custom orders. Quick response & competitive pricing.', '/logo.png', now()),
('support', 'Customer Support | Help & Contact', 'Need help with your order or booking? Contact Creative Caricature Club™ support team. We''re here to assist with orders, payments, delivery & event bookings.', 'caricature support, customer help, contact Creative Caricature Club, order help, payment issue, delivery support, event booking help, caricature customer service', 'Customer Support — Creative Caricature Club™', 'Get help with your orders, payments, delivery & event bookings. Our support team is here for you.', '/logo.png', now()),
('workshop', 'Caricature Workshop | Learn Caricature Drawing', 'Join our caricature drawing workshops and learn from professional artists. Online & offline sessions available. Perfect for beginners & aspiring artists across India.', 'caricature workshop, learn caricature drawing, art workshop India, caricature class online, drawing workshop Mumbai, caricature training, beginner art class, learn cartoon drawing', 'Caricature Workshop — Learn From Pro Artists', 'Join caricature drawing workshops led by professional artists. Online & offline sessions for all skill levels.', '/logo.png', now())
ON CONFLICT (id) DO UPDATE SET
  page_title = EXCLUDED.page_title,
  meta_description = EXCLUDED.meta_description,
  seo_keywords = EXCLUDED.seo_keywords,
  og_title = EXCLUDED.og_title,
  og_description = EXCLUDED.og_description,
  og_image = EXCLUDED.og_image,
  updated_at = now();
